#!/usr/bin/env bash
# Install nginx, Listening port 80, Print "Holberton School", Start nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80/tcp
sudo chmod a+w /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
