#!/usr/bin/env bash
# Install nginx, Listening port 80, Print "Holberton School", Start nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod a+w /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
service nginx start
