#!/usr/bin/env bash
# Bash script that Displays many things xD
sudo touch /var/run/holbertonscript.pid
echo "$$" > /var/run/holbertonscript.pid
while true
do
	trap 'echo "I hate the kill command" ; sudo rm /var/run/holbertonscript.pid' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	echo "To infinity and beyond"
	sleep 2
	trap 'sudo rm /var/run/holbertonscript.pid' SIGQUIT
done
