#!/usr/bin/env bash
# This script is displaying "bad luck" and numbers
i=1
while [ $i -le 20 ]
	do
		echo "$i"
		case $i in
		#case 1
			4) echo "bad luck from China" ;;
		#case 2
			9) echo "bad luck from Japan" ;;
		#case 3
			17) echo "bad luck from Italy" ;;
		esac
		i=$(( i+1 ))
	done
